pipeline {
  agent {
    docker {
      image 'docker-proxy.hljzj.tech/maven:3.8.5-openjdk-17-slim'
      args '-v $ROOT/.m2:/root/.m2'
    }
  }
  stages {
    stage('build') {
      steps {
        sh 'mvn -DskipTests clean package'
        sh 'tar -cvf app.tar dist'
      }
    }
    stage('publish') {
      steps {
        archiveArtifacts 'app.tar'
      }
    }
  }
}