pipeline {
  agent {
    docker {
      image 'docker-proxy.hljzj.tech/maven:3.8.5-openjdk-17-slim'
      args '-v $ROOT/.m2:/root/.m2'
    }
  }

  environment {
      DIST_DIR = "${env.JOB_NAME}"
      BASE_IMAGE = "docker-proxy.hljzj.tech/openjdk:17-buster"
      APP_KEY = "${env.JOB_NAME}"
      MX_MEMORY = "400m"
      MX_CPU = 4
      DIST_COMMAND = """
      CN="${env.APP_KEY.replaceAll('[^a-zA-Z0-9_]', '_')}"
      docker stop \$CN 2>/dev/null
      docker rm \$CN 2>/dev/null
      docker run -dit \
                --memory='${env.MX_MEMORY}' \
                --cpus='${env.MX_CPU}' \
                 --restart=always \
                 --network=subnet \
                 --name \$CN \
                 -v ${env.AGENT_HOME}/${env.DIST_DIR}:/app \
                 -w /app \
                 -e server.ssl.enabled=false \
                 -e server.address=0.0.0.0 \
                 -e server.port=80 \
                 ${env.BASE_IMAGE} \
                 java -jar app.jar
      """
  }

  stages {
    stage('build') {
      steps {
        sh 'mvn -DskipTests clean package'
      }
    }

    stage('publish') {
      steps {
        sh 'tar -cvf app.tar dist'
        archiveArtifacts 'app.tar'
      }
    }

    stage('deploy') {
      steps {
        sshPublisher failOnError: true, publishers: [sshPublisherDesc(configName: 'DEV', transfers: [sshTransfer(cleanRemote: true, excludes: '',execCommand: "${env.DIST_COMMAND}", execTimeout: 120000, flatten: false, makeEmptyDirs: false, noDefaultExcludes: false, patternSeparator: '[, ]+',remoteDirectory: "${env.DIST_DIR}", remoteDirectorySDF: false, removePrefix: 'dist', sourceFiles: 'dist/**')], usePromotionTimestamp: false, useWorkspaceInPromotion: false, verbose: true)]
      }
    }
  }
}