pipeline {
  agent {
    docker {
      image 'docker-proxy.hljzj.tech/maven:3.8.5-openjdk-17-slim'
      args '-v $ROOT/.m2:/root/.m2'
    }
  }

  environment {
      DIST_DIR = "${env.JOB_NAME}"
      BASE_IMAGE = "docker-proxy.hljzj.tech/openjdk:17-buster"
      DIST_COMMAND = """
      docker stop ${env.JOB_BASE_NAME} 2>/dev/null
      docker rm ${env.JOB_BASE_NAME} 2>/dev/null
      docker run -dit \
                 --restart=always \
                 --name ${env.JOB_BASE_NAME} \
                 -v ${env.AGENT_HOME}/${env.DIST_DIR}:/app \
                 -w /app \
                 ${env.BASE_IMAGE} \
                 java -jar app.jar
      """
  }

  stages {
    stage('build') {
      steps {
        sh 'mvn -DskipTests clean package'
      }
    }

    stage('publish') {
      steps {
        sh 'tar -cvf app.tar dist'
        archiveArtifacts 'app.tar'
      }
    }

    stage('deploy') {
      steps {
        sshPublisher failOnError: true, publishers: [sshPublisherDesc(configName: 'DEV', transfers: [sshTransfer(cleanRemote: false, excludes: '',execCommand: "${env.DIST_COMMAND}", execTimeout: 120000, flatten: false, makeEmptyDirs: false, noDefaultExcludes: false, patternSeparator: '[, ]+',remoteDirectory: "${env.DIST_DIR}", remoteDirectorySDF: false, removePrefix: 'dist', sourceFiles: 'dist/**')], usePromotionTimestamp: false, useWorkspaceInPromotion: false, verbose: true)]
      }
    }
  }
}