
-- ----------------------------
-- View structure for v_sys_user_
-- ----------------------------
CREATE
OR REPLACE VIEW `v_sys_user_` AS
select `t`.`id_`                   AS `id_`,
       `t`.`dept_id_`              AS `dept_id_`,
       `t`.`dept_identity_`        AS `dept_identity_`,
       `t`.`username_`             AS `username_`,
       `t`.`password_`             AS `password_`,
       `t`.`mask_v_`               AS `mask_v_`,
       `t`.`old_password_`         AS `old_password_`,
       `t`.`password_policy_`      AS `password_policy_`,
       `t`.`password_expired_`     AS `password_expired_`,
       `t`.`nickname_`             AS `nickname_`,
       `t`.`realname_`             AS `realname_`,
       `t`.`sex_`                  AS `sex_`,
       `t`.`card_type_`            AS `card_type_`,
       `t`.`card_no_`              AS `card_no_`,
       `t`.`phone_`                AS `phone_`,
       `t`.`email_`                AS `email_`,
       `t`.`work_addr_`            AS `work_addr_`,
       `t`.`work_unit_`            AS `work_unit_`,
       `t`.`work_pos_`             AS `work_pos_`,
       `t`.`work_rank_`            AS `work_rank_`,
       `t`.`home_addr_`            AS `home_addr_`,
       `t`.`home_phone_`           AS `home_phone_`,
       `t`.`source_`               AS `source_`,
       `t`.`sort_`                 AS `sort_`,
       `t`.`status_`               AS `status_`,
       `t`.`account_lock_`         AS `account_lock_`,
       `t`.`owner_user_id_`        AS `owner_user_id_`,
       `t`.`owner_user_account_`   AS `owner_user_account_`,
       `t`.`owner_dept_id_`        AS `owner_dept_id_`,
       `t`.`owner_dept_code_`      AS `owner_dept_code_`,
       `t`.`owner_dept_name_`      AS `owner_dept_name_`,
       `t`.`create_by_`            AS `create_by_`,
       `t`.`create_time_`          AS `create_time_`,
       `t`.`update_by_`            AS `update_by_`,
       `t`.`update_time_`          AS `update_time_`,
       `t`.`last_change_password_` AS `last_change_password_`,
       `t1`.`node_key_`            AS `node_key_`,
       `t1`.`node_path_`           AS `node_path_`,
       `t1`.`key_`                 AS `dept_key_`,
       `t1`.`name_`                AS `dept_name_`,
       `t1`.`alias_`               AS `dept_alias_`,
       `t1`.`short_name_`          AS `dept_short_name_`,
       `t1`.`type_`                AS `dept_type_`,
       `t1`.`usc_no_`              AS `dept_usc_no_`,
       `t1`.`addr_no_`             AS `dept_addr_no_`
from (`sys_user_` `t` left join `sys_dept_` `t1` on ((`t1`.`id_` = `t`.`dept_id_`)));

-- ----------------------------
-- View structure for v_sys_dept_member_user_
-- ----------------------------
CREATE
OR REPLACE VIEW `v_sys_dept_member_user_` AS
select `v_sys_user_`.`id_`                   AS `id_`,
       `v_sys_user_`.`dept_id_`              AS `dept_id_`,
       `v_sys_user_`.`dept_identity_`        AS `dept_identity_`,
       `v_sys_user_`.`username_`             AS `username_`,
       `v_sys_user_`.`password_`             AS `password_`,
       `v_sys_user_`.`mask_v_`               AS `mask_v_`,
       `v_sys_user_`.`old_password_`         AS `old_password_`,
       `v_sys_user_`.`password_policy_`      AS `password_policy_`,
       `v_sys_user_`.`password_expired_`     AS `password_expired_`,
       `v_sys_user_`.`nickname_`             AS `nickname_`,
       `v_sys_user_`.`realname_`             AS `realname_`,
       `v_sys_user_`.`sex_`                  AS `sex_`,
       `v_sys_user_`.`card_type_`            AS `card_type_`,
       `v_sys_user_`.`card_no_`              AS `card_no_`,
       `v_sys_user_`.`phone_`                AS `phone_`,
       `v_sys_user_`.`email_`                AS `email_`,
       `v_sys_user_`.`work_addr_`            AS `work_addr_`,
       `v_sys_user_`.`work_unit_`            AS `work_unit_`,
       `v_sys_user_`.`work_pos_`             AS `work_pos_`,
       `v_sys_user_`.`work_rank_`            AS `work_rank_`,
       `v_sys_user_`.`home_addr_`            AS `home_addr_`,
       `v_sys_user_`.`home_phone_`           AS `home_phone_`,
       `v_sys_user_`.`source_`               AS `source_`,
       `v_sys_user_`.`sort_`                 AS `sort_`,
       `v_sys_user_`.`status_`               AS `status_`,
       `v_sys_user_`.`account_lock_`         AS `account_lock_`,
       `v_sys_user_`.`owner_user_id_`        AS `owner_user_id_`,
       `v_sys_user_`.`owner_user_account_`   AS `owner_user_account_`,
       `v_sys_user_`.`owner_dept_id_`        AS `owner_dept_id_`,
       `v_sys_user_`.`owner_dept_code_`      AS `owner_dept_code_`,
       `v_sys_user_`.`owner_dept_name_`      AS `owner_dept_name_`,
       `v_sys_user_`.`create_by_`            AS `create_by_`,
       `v_sys_user_`.`create_time_`          AS `create_time_`,
       `v_sys_user_`.`update_by_`            AS `update_by_`,
       `v_sys_user_`.`update_time_`          AS `update_time_`,
       `v_sys_user_`.`last_change_password_` AS `last_change_password_`,
       `v_sys_user_`.`node_key_`             AS `node_key_`,
       `v_sys_user_`.`node_path_`            AS `node_path_`,
       `v_sys_user_`.`dept_key_`             AS `dept_key_`,
       `v_sys_user_`.`dept_name_`            AS `dept_name_`,
       `v_sys_user_`.`dept_alias_`           AS `dept_alias_`,
       `v_sys_user_`.`dept_short_name_`      AS `dept_short_name_`,
       `v_sys_user_`.`dept_type_`            AS `dept_type_`,
       `v_sys_user_`.`dept_usc_no_`          AS `dept_usc_no_`,
       `v_sys_user_`.`dept_addr_no_`         AS `dept_addr_no_`,
       1                                     AS `owner_type`
from `v_sys_user_`
union all
select `t`.`id_`                   AS `id_`,
       `t1`.`id_`                  AS `dept_id_`,
       `p`.`identity_`             AS `dept_identity_`,
       `t`.`username_`             AS `username_`,
       `t`.`password_`             AS `password_`,
       `t`.`mask_v_`               AS `mask_v_`,
       `t`.`old_password_`         AS `old_password_`,
       `t`.`password_policy_`      AS `password_policy_`,
       `t`.`password_expired_`     AS `password_expired_`,
       `t`.`nickname_`             AS `nickname_`,
       `t`.`realname_`             AS `realname_`,
       `t`.`sex_`                  AS `sex_`,
       `t`.`card_type_`            AS `card_type_`,
       `t`.`card_no_`              AS `card_no_`,
       `t`.`phone_`                AS `phone_`,
       `t`.`email_`                AS `email_`,
       `t`.`work_addr_`            AS `work_addr_`,
       `t`.`work_unit_`            AS `work_unit_`,
       `t`.`work_pos_`             AS `work_pos_`,
       `t`.`work_rank_`            AS `work_rank_`,
       `t`.`home_addr_`            AS `home_addr_`,
       `t`.`home_phone_`           AS `home_phone_`,
       `t`.`source_`               AS `source_`,
       `t`.`sort_`                 AS `sort_`,
       `t`.`status_`               AS `status_`,
       `t`.`account_lock_`         AS `account_lock_`,
       `t`.`owner_user_id_`        AS `owner_user_id_`,
       `t`.`owner_user_account_`   AS `owner_user_account_`,
       `t`.`owner_dept_id_`        AS `owner_dept_id_`,
       `t`.`owner_dept_code_`      AS `owner_dept_code_`,
       `t`.`owner_dept_name_`      AS `owner_dept_name_`,
       `t`.`create_by_`            AS `create_by_`,
       `t`.`create_time_`          AS `create_time_`,
       `t`.`update_by_`            AS `update_by_`,
       `t`.`update_time_`          AS `update_time_`,
       `t`.`last_change_password_` AS `last_change_password_`,
       `t1`.`node_key_`            AS `node_key_`,
       `t1`.`node_path_`           AS `node_path_`,
       `t1`.`key_`                 AS `dept_key_`,
       `t1`.`name_`                AS `dept_name_`,
       `t1`.`alias_`               AS `dept_alias_`,
       `t1`.`short_name_`          AS `dept_short_name_`,
       `t1`.`type_`                AS `dept_type_`,
       `t1`.`usc_no_`              AS `dept_usc_no_`,
       `t1`.`addr_no_`             AS `dept_addr_no_`,
       2                           AS `owner_type`
from ((`sys_dept_external_user_` `p` left join `sys_user_` `t`
       on ((`t`.`id_` = `p`.`user_id_`))) left join `sys_dept_` `t1` on ((`t1`.`id_` = `p`.`dept_id_`)));
